/**
 * Flash account — utility-focused profile and address management on the established
 * paper-white retail field, with Flash Volt reserved for live preference actions.
 */
import { ArrowRight, ChevronRight, LogIn, MapPin, PackageCheck, Plus, Trash2, UserRound, Zap } from "lucide-react";
import { Link } from "react-router-dom";
import { useCommerce } from "@/contexts/CommerceContext";
import { useAuth } from "@/contexts/AuthContext";
import SafeImage from "@/components/common/SafeImage";

export default function Account() {
  const { addresses, orders, deleteAddress, setDefaultAddress } = useCommerce();
  const { user } = useAuth();
  if (!user) return <section className="account-page shell"><div className="auth-gate"><aside className="auth-gate__signal"><span><Zap fill="currentColor" /></span><p className="eyebrow">Flash access</p><h2>Saved speed.<br /><em>All yours.</em></h2><p>Build a faster route through every find, address, and order update.</p><Link to="/shop">Explore the edit <ArrowRight size={16} /></Link></aside><div className="auth-gate__content"><UserRound size={31} /><p className="eyebrow">Your Flash space</p><h1>Sign in to tune your account.</h1><p>Keep saved finds, delivery details and order activity in one fast lane.</p><Link className="lime-button" to="/login">Sign in <LogIn size={17} /></Link></div></div></section>;
  return <section className="account-page shell"><div className="page-title"><p className="eyebrow">Your Flash space</p><h1>Account, tuned in.</h1><p>Your account preferences and activity stay connected on this browser.</p></div><div className="account-grid"><aside className="account-rail"><div className="account-avatar">{user.avatar ? <SafeImage src={user.avatar} alt="" /> : <UserRound size={24} />}</div><b>{user.name}</b><span>{user.email ?? user.phone ?? "Flash account"}</span><nav><Link className="is-active" to="/account">Profile</Link><Link to="/orders">Orders <ChevronRight size={15} /></Link><Link to="/wishlist">Wishlist <ChevronRight size={15} /></Link><Link to="/flash-club">Flash Club <ChevronRight size={15} /></Link></nav></aside><div className="account-content"><section className="account-welcome"><div><p className="eyebrow">{user.flashClub ? "Flash Club member" : "Flash member space"}</p><h2>Keep your next move close.</h2><p>Your saved finds, delivery addresses, and new order activity will live here.</p></div><Link className="black-button" to="/shop">Shop the edit</Link></section><section className="account-orders"><div className="account-section-head"><div><PackageCheck size={19} /><h2>Order activity</h2></div><Link to="/orders">See all <ChevronRight size={16} /></Link></div>{orders.length ? orders.slice(0, 2).map((order) => <article key={order.id}><div><span className="status-pill">{order.status}</span><b>{order.id}</b><small>Placed {order.createdAt}</small></div><Link to="/orders">Track order <ChevronRight size={15} /></Link></article>) : <div className="account-empty"><PackageCheck size={20} /><p><b>No orders placed yet.</b><span>Explore deals and start shopping!</span></p><Link to="/shop" className="lime-button">Shop Now</Link></div>}</section><section className="saved-addresses" id="addresses"><div className="account-section-head"><div><MapPin size={19} /><h2>Saved addresses</h2></div><Link to="/checkout"><Plus size={15} /> Add at checkout</Link></div>{addresses.length ? <div className="address-list">{addresses.map((address) => <article key={address.id}><div><b>{address.label} {address.isDefault && <em>Default</em>}</b><strong>{address.name}</strong><p>{address.line1}, {address.city}, {address.state} — {address.pincode}</p><small>{address.phone}</small></div><div className="address-actions">{!address.isDefault && <button onClick={() => setDefaultAddress(address.id)}>Set default</button>}{addresses.length > 1 && <button onClick={() => deleteAddress(address.id)} aria-label="Delete address"><Trash2 size={15} /></button>}</div></article>)}</div> : <div className="account-empty account-empty--address"><MapPin size={20} /><p><b>No delivery addresses yet.</b><span>Add one during checkout when you are ready to move.</span></p><Link to="/checkout" className="black-button">Add address</Link></div>}</section></div></div></section>;
}
