/**
 * Flash orders — a clean user-driven activity rail. New visitors see no seeded purchases;
 * cards enter this view only after checkout creates an order in browser-local state.
 */
import { ChevronRight, MapPin, PackageCheck, Truck, Zap } from "lucide-react";
import { Link } from "react-router-dom";
import { useCommerce } from "@/contexts/CommerceContext";
import { formatINR, getProduct } from "@/data/mockProducts";
import SafeImage from "@/components/common/SafeImage";

export default function Orders() {
  const { orders } = useCommerce();
  return <section className="orders-page shell"><div className="page-title"><p className="eyebrow">Order activity</p><h1>Every move, mapped.</h1><p>Completed checkouts appear here with the next delivery steps.</p></div><div className="orders-runway"><aside className="orders-runway__signal"><Zap fill="currentColor" /><p className="eyebrow">Flash dispatch</p><h2>Finds.<br /><em>In motion.</em></h2><p>Your order flow begins at checkout, then keeps pace right here.</p><div><span>01</span><b>Find the next one</b><span>02</span><b>Set your delivery stop</b><span>03</span><b>Follow every move</b></div></aside><div className="orders-list">{orders.length ? orders.map((order) => <article key={order.id} className="order-card"><div className="order-card__head"><div><span className="status-pill">{order.status}</span><h2>{order.id}</h2><p>Placed {order.createdAt}</p></div><div><strong>{formatINR(order.total)}</strong><Link to="/account">Delivery details <ChevronRight size={15} /></Link></div></div><div className="order-products">{order.lines.map((line) => { const product = getProduct(line.productId); return product && <Link to={`/product/${product.id}`} key={`${order.id}-${product.id}-${line.variantSku ?? line.color}-${line.size}`}><SafeImage src={line.image ?? product.image} alt={product.name} /><span><b>{product.name}</b><small>{[line.colorName ?? line.color, line.size].filter(Boolean).join(" · ")} · Qty {line.quantity}</small></span></Link>; })}</div><div className="order-track"><div><PackageCheck size={17} /><span><b>Order confirmed</b><small>We have the request.</small></span></div><i /><div className={order.status !== "Processing" ? "is-active" : ""}><Truck size={17} /><span><b>In transit</b><small>{order.status === "Processing" ? "Preparing to move." : "Moving toward you."}</small></span></div><i /><div className={order.status === "Delivered" ? "is-active" : ""}><MapPin size={17} /><span><b>Delivered</b><small>{order.status === "Delivered" ? "Arrival confirmed." : "Next stop: your door."}</small></span></div></div></article>) : <div className="orders-empty"><PackageCheck size={34} /><p className="eyebrow">Order activity</p><h2>No orders placed yet.</h2><p>Explore deals and start shopping!</p><Link className="lime-button" to="/shop">Shop Now</Link></div>}</div></div></section>;
}
